variable decl. = [ "const" ], type name, {actual var. decl., [ "=", expr list]}+(","), ";" ;

actual var. decl. = variable name, [ array declaration ];

array decl. = {"[", [constant expression], "]"}+;

expression list = (~, ~, expression) | ("{", { expression list}+(",") ,"}") ;