function decl. = type name, function name, "(", parameter list ,")", block ;

parameter list = { parameter declaration }*(",") ;

parameter decl. = [ "const" ] type name, ["*"], parameter name, { "[ ]" }* ;
