procedure decl. = "void", procedure name, "(", parameter list ,")", block ;

parameter list = { parameter declaration }*(",") ;

parameter decl. = type name, parameter name ;

parameter name = identifier ;

block = "{", {statement}* ,"}" ;
