class declaration = "class", class name, block ;

class name = identifier ;

block = "{", { [ access modifier, field declaration | constructor declaration | method delcaration | property declaration ] }+ "}" ;

access modifier = ("public" | "private") ;