method declaration = scope, ["static"], return type, method name, "(", parameter list, ")", block ;

scope = "public" | "private";

parameter list = {parameter delcaration}*(",") ;

parameter declaration = type name, parameter name ;

block = "{", statements, "}" ;

statements = {statement, ";"}* ;

return type = identifier ;

method name = identifier ;